package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"
)

// palettePath is the per-user override file. webdiff reads it at startup
// and inlines its contents after style.css so any :root custom-properties
// it defines win over the embedded defaults.
func palettePath() string {
	if dir, err := os.UserConfigDir(); err == nil {
		return filepath.Join(dir, "webdiff", "palette.css")
	}
	return ""
}

func loadPalette() string {
	p := palettePath()
	if p == "" {
		return ""
	}
	b, err := os.ReadFile(p)
	if err != nil {
		return ""
	}
	return string(b)
}

// runPalette interactively queries the controlling terminal for its
// 16 ANSI colours, default foreground, and default background via OSC
// escape sequences, then writes a `:root { ... }` CSS block to stdout.
//
// Pipe it into the override file to make webdiff render with your real
// terminal palette:
//
//	webdiff palette > ~/.config/webdiff/palette.css
//
// We use `stty` to flip /dev/tty into raw mode (no extra Go deps), drain
// responses for ~2 s, and parse `rgb:RR/GG/BB` or `rgb:RRRR/GGGG/BBBB`
// into 8-bit hex. Indices the terminal didn't answer for are skipped —
// tmux/screen often strip OSC responses, in which case re-run from
// outside the multiplexer.
func runPalette() error {
	tty, err := os.OpenFile("/dev/tty", os.O_RDWR, 0)
	if err != nil {
		return err
	}
	defer tty.Close()

	saveCmd := exec.Command("stty", "-g")
	saveCmd.Stdin = tty
	saved, err := saveCmd.Output()
	if err != nil {
		return fmt.Errorf("stty -g (is this a real terminal?): %w", err)
	}
	savedSpec := strings.TrimSpace(string(saved))

	rawCmd := exec.Command("stty", "raw", "-echo", "min", "0", "time", "1")
	rawCmd.Stdin = tty
	if err := rawCmd.Run(); err != nil {
		return fmt.Errorf("stty raw: %w", err)
	}
	defer func() {
		restore := exec.Command("stty", savedSpec)
		restore.Stdin = tty
		_ = restore.Run()
	}()

	// Probe with one OSC 10 query first. If nothing comes back in ~300ms
	// we're almost certainly inside a multiplexer or wrapper that swallows
	// OSC replies, and the full batch would just stall for 2s before
	// erroring anyway.
	if _, err := tty.WriteString("\x1b]10;?\x07"); err != nil {
		return fmt.Errorf("write OSC probe: %w", err)
	}
	probeDeadline := time.Now().Add(300 * time.Millisecond)
	var probeBuf []byte
	probeTmp := make([]byte, 256)
	for time.Now().Before(probeDeadline) {
		n, _ := tty.Read(probeTmp)
		if n > 0 {
			probeBuf = append(probeBuf, probeTmp[:n]...)
			break
		}
	}
	if len(probeBuf) == 0 {
		return fmt.Errorf("re-run `webdiff palette` directly in your terminal emulator, outside any multiplexer or remote-shell wrapper: this session swallowed an OSC 10 color query (no reply in 300ms)")
	}

	var queries strings.Builder
	for i := 0; i < 16; i++ {
		fmt.Fprintf(&queries, "\x1b]4;%d;?\x07", i)
	}
	queries.WriteString("\x1b]10;?\x07")
	queries.WriteString("\x1b]11;?\x07")
	if _, err := tty.WriteString(queries.String()); err != nil {
		return fmt.Errorf("write OSC: %w", err)
	}

	// Drain for up to ~2s. Each Read blocks for up to 0.1s thanks to
	// `stty time 1`, so we just keep reading until we've been idle for
	// a couple of empty rounds or the deadline trips.
	deadline := time.Now().Add(2 * time.Second)
	buf := probeBuf
	tmp := make([]byte, 4096)
	idleRounds := 0
	for time.Now().Before(deadline) {
		n, err := tty.Read(tmp)
		if n > 0 {
			buf = append(buf, tmp[:n]...)
			idleRounds = 0
			continue
		}
		if err != nil {
			break
		}
		idleRounds++
		if idleRounds >= 5 && len(buf) > 0 {
			break
		}
	}

	indexed, fg, bg := parsePaletteResponse(string(buf))
	if len(indexed) == 0 && fg == "" && bg == "" {
		return fmt.Errorf("terminal replied to the probe but not to any OSC 4/10/11 queries — it may not support indexed-color or default-color queries")
	}

	fmt.Println("/* Generated by `webdiff palette`. Override the embedded defaults. */")
	fmt.Println(":root {")
	for i := 0; i < 16; i++ {
		if c, ok := indexed[i]; ok {
			fmt.Printf("  --color-%-2d: %s;\n", i, c)
		}
	}
	if fg != "" {
		fmt.Printf("  --fg: %s;\n", fg)
	}
	if bg != "" {
		fmt.Printf("  --bg: %s;\n", bg)
	}
	fmt.Println("}")
	return nil
}

// OSC reply shapes we want to parse:
//
//	]4;<index>;rgb:RR/GG/BB     — indexed colour reply for 0-15
//	]10;rgb:RR/GG/BB            — default foreground
//	]11;rgb:RR/GG/BB            — default background
//
// Both BEL (\x07) and ST (\x1b\\) terminators are valid; we don't anchor
// on either, just on the body shape. Each channel may be 1, 2, 3, or
// 4 hex digits depending on the terminal.
var (
	oscIndexedRE = regexp.MustCompile(`\]4;(\d+);rgb:([0-9a-fA-F]+)/([0-9a-fA-F]+)/([0-9a-fA-F]+)`)
	oscDefaultRE = regexp.MustCompile(`\](1[01]);rgb:([0-9a-fA-F]+)/([0-9a-fA-F]+)/([0-9a-fA-F]+)`)
)

func parsePaletteResponse(s string) (indexed map[int]string, fg, bg string) {
	indexed = map[int]string{}
	for _, m := range oscIndexedRE.FindAllStringSubmatch(s, -1) {
		idx, err := strconv.Atoi(m[1])
		if err != nil || idx < 0 || idx >= 16 {
			continue
		}
		indexed[idx] = fmt.Sprintf("#%02x%02x%02x", scaleHex(m[2]), scaleHex(m[3]), scaleHex(m[4]))
	}
	for _, m := range oscDefaultRE.FindAllStringSubmatch(s, -1) {
		hex := fmt.Sprintf("#%02x%02x%02x", scaleHex(m[2]), scaleHex(m[3]), scaleHex(m[4]))
		switch m[1] {
		case "10":
			fg = hex
		case "11":
			bg = hex
		}
	}
	return indexed, fg, bg
}

// scaleHex turns the hex digits between two `/` separators into an
// 8-bit channel value. Terminals reply in either 2-digit (`ff`) or
// 4-digit (`ffff`) form per channel; we want a single byte either way.
func scaleHex(s string) byte {
	n, err := strconv.ParseUint(s, 16, 32)
	if err != nil {
		return 0
	}
	switch len(s) {
	case 1:
		return byte(n) * 0x11
	case 2:
		return byte(n)
	case 3:
		return byte(n >> 4)
	case 4:
		return byte(n >> 8)
	}
	return byte(n)
}
