#!/usr/bin/env bash
# Registers a `webdiff://` URL handler on *this* Mac so the diff UI's
# terminal button can open a Ghostty window ssh'd into the sandbox.
#
# Run this on your laptop, not on the sandbox:
#
#     deploy/install-url-handler.sh <ssh-host>
#
# where <ssh-host> is the same value the server was started with
# (-ssh-host), i.e. whatever `ssh <host>` you'd type by hand.
#
# Zed needs none of this — it registers zed:// itself and the buttons use
# its documented zed://ssh/<host>/<path> hotlink form. Ghostty has no
# inbound URL scheme, so this bridges the gap.
#
# Safe to re-run; it replaces the previously installed handler.
set -euo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
	echo "This installs a macOS URL handler; run it on your Mac." >&2
	exit 1
fi

if [[ $# -ne 1 || -z "${1//[[:space:]]/}" ]]; then
	echo "usage: $(basename "$0") <ssh-host>" >&2
	exit 1
fi
ssh_host="$1"

# The host is pinned at install time and the handler refuses any URL
# naming a different one. This matters: once webdiff:// is registered,
# *any* page your browser loads can hand the OS one of these URLs, so the
# handler has to assume its input is hostile. Pinning means the worst a
# hostile page can do is open a shell on a host you'd already trusted.
if [[ ! "$ssh_host" =~ ^[A-Za-z0-9._@-]+$ ]]; then
	echo "refusing suspicious ssh host: $ssh_host" >&2
	exit 1
fi

support_dir="$HOME/Library/Application Support/webdiff"
helper="$support_dir/open-handler.sh"
app_dir="$HOME/Applications/webdiff URL Handler.app"

echo "==> Installing handler script to $helper"
mkdir -p "$support_dir"

# ALLOWED_HOST is baked in above the shebang's reach on purpose — the
# handler never trusts the URL to tell it where to connect.
cat > "$helper" <<HELPER
#!/usr/bin/env bash
# Generated by webdiff's deploy/install-url-handler.sh. Edits will be lost
# on reinstall. Handles webdiff://ghostty?host=<host>&dir=<abs-path>.
set -euo pipefail

ALLOWED_HOST='$ssh_host'
HELPER

cat >> "$helper" <<'HELPER'

url="${1:-}"
[[ -n "$url" ]] || { echo "no URL given" >&2; exit 1; }

# Percent-decoding via printf: escape any literal backslashes first so
# they can't be read as \x sequences, then turn %XX into \xXX.
urldecode() {
	local s="${1//\\/\\\\}"
	printf '%b' "${s//%/\\x}"
}

rest="${url#webdiff://}"
if [[ "$rest" == "$url" ]]; then
	echo "not a webdiff:// URL" >&2
	exit 1
fi
action="${rest%%\?*}"
query="${rest#*\?}"
[[ "$query" != "$rest" ]] || query=""

host="" dir=""
IFS='&' read -ra pairs <<< "$query"
for pair in "${pairs[@]}"; do
	case "$pair" in
		host=*) host="$(urldecode "${pair#host=}")" ;;
		dir=*)  dir="$(urldecode "${pair#dir=}")" ;;
	esac
done

if [[ "$action" != "ghostty" ]]; then
	echo "unsupported webdiff:// action: $action" >&2
	exit 1
fi

# Only the host this handler was installed for. A mismatch means the URL
# came from somewhere other than the webdiff instance we trust.
if [[ "$host" != "$ALLOWED_HOST" ]]; then
	echo "refusing host '$host' (this handler only opens '$ALLOWED_HOST')" >&2
	exit 1
fi

# The directory is interpolated into a remote shell command, so keep it to
# an absolute path of boring characters. Notably no quotes, backslashes,
# $, backticks or semicolons, which is what makes the single-quoting below
# sufficient.
if [[ "$dir" != /* || ! "$dir" =~ ^[A-Za-z0-9._/@+-]+$ ]]; then
	echo "refusing suspicious directory: $dir" >&2
	exit 1
fi

# $SHELL stays single-quoted so the *remote* shell expands it. `exec`
# replaces ssh's login shell so closing the shell closes the window.
remote_cmd="cd '$dir' && exec \$SHELL -l"

# `open -na … --args` is how you pass Ghostty CLI flags on macOS; running
# the binary in the bundle directly triggers an unsuppressable "Allow
# Ghostty to Execute" prompt on every invocation. -n means a new instance
# each time, so quit-after-last-window-closed keeps them from piling up.
exec open -na Ghostty.app --args \
	--quit-after-last-window-closed=true \
	-e ssh -t "$host" "$remote_cmd"
HELPER

chmod 755 "$helper"

echo "==> Building app bundle at $app_dir"
mkdir -p "$HOME/Applications"
rm -rf "$app_dir"

# A bare shell script can't receive the open-URL Apple Event, so the thing
# actually registered is a tiny AppleScript app whose only job is to hand
# the URL to the script above. Errors propagate into a dialog, which is
# the feedback path for a rejected URL.
osa_src="$(mktemp -t webdiff-url-handler).applescript"
trap 'rm -f "$osa_src"' EXIT
cat > "$osa_src" <<'OSA'
on open location this_URL
	set helper to (POSIX path of (path to home folder)) & "Library/Application Support/webdiff/open-handler.sh"
	do shell script quoted form of helper & " " & quoted form of this_URL
end open location
OSA
osacompile -o "$app_dir" "$osa_src"

plist="$app_dir/Contents/Info.plist"
/usr/libexec/PlistBuddy \
	-c "Add :CFBundleIdentifier string dev.webdiff.urlhandler" \
	-c "Add :CFBundleURLTypes array" \
	-c "Add :CFBundleURLTypes:0 dict" \
	-c "Add :CFBundleURLTypes:0:CFBundleURLName string webdiff" \
	-c "Add :CFBundleURLTypes:0:CFBundleURLSchemes array" \
	-c "Add :CFBundleURLTypes:0:CFBundleURLSchemes:0 string webdiff" \
	-c "Add :LSUIElement bool true" \
	"$plist" >/dev/null

# Launch Services caches bundle metadata; without an explicit register the
# new scheme can go unnoticed until a logout.
echo "==> Registering with Launch Services"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
	-f "$app_dir"

echo
echo "Installed. webdiff:// now opens Ghostty ssh'd to '$ssh_host'."
echo "Test it with:"
echo "  open 'webdiff://ghostty?host=$ssh_host&dir=%2Fhome%2Fubuntu%2Fai'"
echo
echo "The first click will ask you to confirm opening the app — that's macOS"
echo "checking the new handler, and it only asks once."
